---
- name: Install EPEL repo
  yum: name=epel-release state=present
  
- name: Ensure that nginx installed.
  yum: name=nginx state=latest

- name: Make sure a service nginx is running and it in autostart
  ansible.builtin.systemd:
    state: started
    name: nginx
    enabled: yes

- name: Copy index.html
  ansible.builtin.copy:
    src: index.html
    dest: /usr/share/nginx/html 
    follow: yes