---
- hosts: nginx
  become: yes
  remote_user: user
  become_method: sudo
  roles:
    - nginx
    - nodeexporter
    - firewalld
  #  - nginxexporter

#- hosts: prometeus
#  become: yes
#  remote_user: user
#  become_method: sudo
#  roles:
#    - prometeus