---
# tasks file for myrole
- name: install apache # Install Apache
  yum:
    name: httpd
    state:  present

- name: Touch a file # Make index.html
  ansible.builtin.file:
    path: /var/www/html/index.html
    state: touch
    mode: u=rw,g=r,o=r

- name: edit index.html # Edit index.html
  ansible.builtin.lineinfile:
    path: /var/www/html/index.html
    regexp: '^'
    line: IP Adress "{{ http_host }}" CPU "{{ cpu }}" total RAM "{{ ram }}" total HDD "{{ hdd }}"
    state: present

- name: start apache # Start Apache and make autostart
  ansible.builtin.systemd:
    state: started
    name: httpd
    enabled: yes

- name: Get status of Server # Get 200 code
  command: curl -Is "{{ http_host }}"
  register: code

- debug: msg="{{ code }}" # Print 200 code